[supabase]
supabase_url = "https://lmypppmgvuhpdfhysive.supabase.co"
supabase_key = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImxteXBwcG1ndnVocGRmaHlzaXZlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDczNzAxODUsImV4cCI6MjA2Mjk0NjE4NX0.W6XPU8mTfJmEitH0Hf8VQtc7ScgqMaGFo2lzypl2m44"

[gcp_service_account]
type = "service_account"
project_id = "eng-contact-461003-n6"
private_key_id = "44c1beb179ab3ac244fdb7be9dbaf88d8eb3dc9e"
private_key = """-----BEGIN PRIVATE KEY-----
MIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQCvHrum87aHoFV+
bDnm3Shpp8UTRu18lBQh3hZZCJSRmzsJ0wqLicMPnvs5xwpdKWtQhelaX85vZXpL
LSuEOAI6VmiGQysuVgOr08K9B2TrpRz3fNNvHYNMeDwoBLPOYTSPemQwp6T5KlSt
AUOvWDgIBc6jFlXlbkwDPyACOHngFml4N4mqldmNPZSaP2y35G3SNIKFuG9cX8s3
WFyKFysrGB5iKVSqmzaf4GVefYytsE0hCdh2HuhITRwo2nliuDaPnu/KBkAMMQDC
n0PZgVIJc+OfOU68cEC+DjD6b6woJD/DPsR3pZhT0tgzVT/SZyS+OxEa04pDR0HE
2LINPSjnAgMBAAECggEAARhY8GaAwzYHotaWwXCrnTGH5CLNlGRcAImM1o9dAntt
MewIb66eXNLP27Yjb0lgMEI4ydsPMEIlssz8WIN90WiTQcJaGvGTF019NRppO/yt
2DGxzsrpSclMswFd2ydfdprmKn8POIxWYuM++Ec9ySBkK5VAV0LKezth/gblYuHZ
Arf9zmo7muk6ph5ZIJ7IwAnEz0W74YBcQqH+tsd79SApzTs6EQW+xF/hscnobzfk
4SJeFyT+M6EyqhUosPSs5CoVPyu1FGjGVibrQYpDxkYUDGkAH6Z2sNnjZZkV9hR1
y2JQQTbc7KzoEJojWEEmxaXicgqwJ+rF9w+lg+xRcQKBgQDhhpVBAnnPlDwIWelw
ell7r/SXI5BjPF7wcOTdev/QgK+BRrx+uBwA3Iv8LVcpZJZn1tHD8GYxx4kR3Qng
vKA6fKTZKS1BCcRjeE033u+GQfhZ8hx7J9IkQBw2SntBez07Kygx6JYHXFMQiMwA
k7plPjlVPKdpv3FSaVAslIdc0QKBgQDGyIKemo0WRYY/Tpm1rOOEnqVqQ7rY3H7D
4Dblvuirl7Kt7yllda+LDmcAxSBrHmuPEkNkQtUgTbY37ZqaCN7s3tXPd/ZNVFfz
pBwSkCioxm3oG9otOhgEJHe01wF/Sgyt3asmr61Oaw9MSyawyfkKynMnClWlf5yK
lLj81tK4NwKBgF6E9ErxybGpE9wAKuk8LgK7xQwPGLWumK+28QSuR0bQmD3bMqb9
bKcjx/uh2RT9Flhg3Tt8pqgYU6dL95bcF19L3B8ztca7XDbANcTDx6mCPp8b7Lnk
/5q3z9slLjFMgGYq+Uapjy94j0uvuahIQeeqw4aozBVy6gC7KKH2giDxAoGAP+fE
PlL3WpqdTwro1YQwXLlX+nKtxfwU8MnLPE8Eo+2P7uT9TPXpqm3F5XR6OJW+BG/d
pITr2YfCNfa4Bh8l88arvBgX4cJkyBoRQFKCD8hDGyShHnsXr3U92rBoddCLhPXH
iRdfQt+eOmvKk3lLDBILtRhYcm01GUQ4uGgjtD8CgYEAlFbFJDcF545uJ/+Pka68
ODFAoZVNs88N1eG5De5aqEYHyJtO4zZRIiNfox3hHbYo/zHxBQLvAQC1NLFVkfUw
tRDCYNvLB5A0tfy6EcVOy3EvLKdToQ62FHTLiXIRYpP2I90Qf6tnz/ebv3dh+Z8D
J/n0yWlzyGVscXJYO6cDQsg=
-----END PRIVATE KEY-----"""
client_email = "sheets-access@eng-contact-461003-n6.iam.gserviceaccount.com"
client_id = "101155037163727576073"
auth_uri = "https://accounts.google.com/o/oauth2/auth"
token_uri = "https://oauth2.googleapis.com/token"
auth_provider_x509_cert_url = "https://www.googleapis.com/oauth2/v1/certs"
client_x509_cert_url = "https://www.googleapis.com/robot/v1/metadata/x509/sheets-access%40eng-contact-461003-n6.iam.gserviceaccount.com"
universe_domain = "googleapis.com"
